services:
  market-streamer:
    image: market-streamer:latest
    container_name: market-streamer
    pull_policy: never
    networks:
      - trading-network
    ports:
      - "8001:8001"
    environment:
      - BIND_ADDR=0.0.0.0:8888
    expose:
      - "8888"

  rsi-algo:
    image: rsi-algo:latest
    container_name: rsi-algo
    pull_policy: never
    depends_on:
      - market-streamer
    networks:
      - trading-network
      - external
    ports:
      - "8002:8002"
      - "9999:9999"  # Expose the signal output port
    environment:
      - STREAMING_SOURCE_IP=market-streamer  # Use service name instead of localhost
      - STREAMING_SOURCE_PORT=8888
      # Database connection settings (external databases)
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=trading_results
      - POSTGRES_USER=trading_user
      - POSTGRES_PASSWORD=trading_pass
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin_pass
      - MONGODB_DATABASE=trading_configs
    expose:
      - "9999"

  trade-simulator:
    image: trade-simulator:latest
    container_name: trade-simulator
    pull_policy: never
    depends_on:
      - rsi-algo
    networks:
      - trading-network
      - external
    ports:
      - "8003:8003"
    environment:
      - ALGORITHM_SOURCE_IP=rsi-algo  # Use service name
      - ALGORITHM_SOURCE_PORT=9999
      # Database connection settings (external databases)
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=trading_results
      - POSTGRES_USER=trading_user
      - POSTGRES_PASSWORD=trading_pass
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin_pass
      - MONGODB_DATABASE=trading_configs
      - MAX_RUNTIME_SECS=8
      # Redis connection settings
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  trading-network:
    driver: bridge
  # Connect to external database network
  external:
    external: true
    name: trading-db-network